[project]
dependencies = [
    "attrs==26.1.0",
    "certifi==2026.6.17",
    "charset-normalizer==3.5.1",
    "exceptiongroup==1.3.1",
    "h11==0.16.0",
    "idna==3.18",
    "iniconfig==2.3.0",
    "outcome==1.3.0.post0",
    "packaging==26.2",
    "pluggy==1.6.0",
    "pygments==2.20.0",
    "pysocks==1.7.1",
    "pytest==9.1.1",
    "requests==2.34.2",
    "selenium==4.45.0",
    "sniffio==1.3.1",
    "sortedcontainers==2.4.0",
    "tomli==2.4.1",
    "trio==0.33.0",
    "trio-websocket==0.12.2",
    "typing-extensions==4.15.0",
    "urllib3==2.7.0",
    "websocket-client==1.9.0",
    "wsproto==1.3.2",
]
name = "cAnnections_test_framework"
requires-python = ">=3.12"
version = "0.0.1"

[tool.pytest]
addopts = ["--import-mode=importlib"]
markers = [
    "body: the test checks the structure or content of the body of the page.",
    "color: the test checks the background-color CSS property of an element.",
    "deselect: the test checks the logic or style of the Deselect button.",
    "game_over: the test checks various scenarios for game endings.",
    "requires_clipboard: the test requires clipboard access, necessitating specific permissions.",
    "share: the test checks the logic of the share button.",
    "shuffle: the test checks the logic of the Shuffle button.",
    "squares: the test checks the logic or style of the selectable square buttons.",
    "submit: the test checks the logic or style of the Submit button."
]
strict = true

[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["ALL"]
ignore = ["CPY001"]
